# Generated by Django 3.2.7 on 2021-10-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.IntegerField(default=0, verbose_name='Budget'),
        ),
    ]
