# Generated by Django 3.2.7 on 2021-09-30 09:27

from django.db import migrations, models
import rest_framework.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, validators=[rest_framework.validators.UniqueValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
    ]
