# Generated by Django 3.2.7 on 2021-09-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=50, verbose_name='Type')),
                ('amount', models.IntegerField(db_index=True, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user_id', to='users.user')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
